version: "3.7"

services:
  spotify-mongo:
    container_name: spotify-mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: spotify
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 8055:27017
    restart: unless-stopped
